### ISSUE TITLE
For Arnaud Tarroux

### ISSUE THREAD

**Issue by sylfabre** [Zenitth/landing#1]
@ArnaudTarroux Arnaud ton compte GitHub utilise encore ton adresse BuyPacker, il faudrait que tu la mettes à jour car on reçoit les emails de GitHub !

**Comment by ArnaudTarroux** [comment]
@sylfabre : Merci de m'avoir remonté ce problème, j'ai supprimé l'adresse BuyPacker de mon compte, dis moi si jamais ça se reproduit.
